# Generated by Django 4.1.13 on 2026-02-25 22:38

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('sentiment', 'Sentiment NLP'), ('regime', 'Regime Detection'), ('reinforcement', 'Reinforcement Learning'), ('prediction', 'Price Prediction')], max_length=30)),
                ('version', models.CharField(default='0.1.0', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('training', 'Training'), ('retired', 'Retired')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(default=apps.dashboard.models.generate_strategy_id, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('asset_class', models.CharField(choices=[('stocks', 'Stocks'), ('futures', 'Futures'), ('crypto', 'Crypto')], default='stocks', max_length=20)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', 'Daily'), ('1w', 'Weekly')], default='1d', max_length=5)),
                ('symbols', models.JSONField(blank=True, default=list, help_text='List of ticker symbols this strategy trades')),
                ('account_numbers', models.CharField(blank=True, default='', help_text='Comma-separated broker_account_id strings where this strategy runs', max_length=255)),
                ('position_size_pct', models.DecimalField(decimal_places=2, default='2.00', help_text='Position size as % of account equity', max_digits=5)),
                ('max_positions', models.IntegerField(default=5)),
                ('stop_loss_pct', models.DecimalField(decimal_places=2, default='2.00', help_text='Stop loss as % from entry', max_digits=5)),
                ('take_profit_pct', models.DecimalField(decimal_places=2, default='4.00', help_text='Take profit as % from entry', max_digits=5)),
                ('ai_model', models.CharField(choices=[('none', 'None (Rules Only)'), ('sentiment', 'Sentiment NLP'), ('regime', 'Regime Detection (HMM)'), ('reinforcement', 'Reinforcement Learning'), ('ensemble', 'Ensemble (All Models)')], default='none', max_length=30)),
                ('ai_confidence_threshold', models.DecimalField(decimal_places=2, default='0.70', help_text='Min confidence score to act on AI signal (0-1)', max_digits=3)),
                ('ai_retrain_freq', models.CharField(default='weekly', max_length=20)),
                ('custom_params', models.JSONField(blank=True, default=dict, help_text='Strategy-specific parameters as JSON')),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
