# Generated by Django 4.1.13 on 2026-02-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirmAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'FTMO 100K Challenge #2'", max_length=100)),
                ('firm', models.CharField(choices=[('trade_the_pool', 'Trade The Pool'), ('ftmo', 'FTMO'), ('topstep', 'Topstep'), ('apex_trader', 'Apex Trader Funding'), ('dna_funded', 'DNA Funded'), ('hyro_trader', 'HyroTrader'), ('crypto_fund_trader', 'Crypto Fund Trader'), ('other', 'Other')], max_length=30)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('phase', models.CharField(choices=[('evaluation', 'Evaluation'), ('verification', 'Verification'), ('funded', 'Funded'), ('suspended', 'Suspended'), ('failed', 'Failed')], default='evaluation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('account_size', models.DecimalField(decimal_places=2, default=50000, help_text='Starting account size ($)', max_digits=15)),
                ('max_daily_drawdown_pct', models.DecimalField(decimal_places=2, default=5.0, help_text="Firm's max daily drawdown % (e.g., 5%)", max_digits=5)),
                ('max_total_drawdown_pct', models.DecimalField(decimal_places=2, default=10.0, help_text="Firm's max total drawdown % (e.g., 10%)", max_digits=5)),
                ('profit_target_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Profit target % to pass the phase (e.g., 10%)', max_digits=5)),
                ('profit_split_pct', models.DecimalField(decimal_places=2, default=80.0, help_text='Your profit split % on funded account (e.g., 80%)', max_digits=5)),
                ('min_trading_days', models.IntegerField(default=10, help_text='Minimum trading days required')),
                ('trading_days_completed', models.IntegerField(default=0)),
                ('challenge_start_date', models.DateField(blank=True, null=True)),
                ('challenge_end_date', models.DateField(blank=True, null=True)),
                ('broker_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prop Firm Account',
                'verbose_name_plural': 'Prop Firm Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_daily_drawdown_pct', models.DecimalField(decimal_places=2, default='5.00', help_text='Maximum daily loss as % of account equity', max_digits=5)),
                ('max_total_drawdown_pct', models.DecimalField(decimal_places=2, default='10.00', help_text='Maximum total drawdown as % of starting equity', max_digits=5)),
                ('max_position_size_pct', models.DecimalField(decimal_places=2, default='5.00', help_text='Maximum position size as % of account equity', max_digits=5)),
                ('max_open_positions', models.IntegerField(default=10, help_text='Maximum number of concurrent open positions')),
                ('max_daily_trades', models.IntegerField(default=50, help_text='Maximum trades per day (PDT awareness)')),
                ('daily_loss_limit', models.DecimalField(decimal_places=2, default='1000.00', help_text='Maximum dollar loss per day before auto-stop', max_digits=15)),
                ('kill_switch_active', models.BooleanField(default=False, help_text='When True, ALL trading is halted immediately')),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Configuration',
                'verbose_name_plural': 'Risk Configurations',
            },
        ),
    ]
