# Generated by Django 4.1.13 on 2026-02-26 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirmPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount requested from the firm', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Withdrawal'), ('approved', 'Firm Approved'), ('deposited', 'Deposited to Bank'), ('rejected', 'Rejected / Denied')], default='pending', max_length=20)),
                ('amount_deposited', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount that hit the bank (after split and crypto fees)', max_digits=15, null=True)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='e.g. Deel, crypto wallet tx hash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='risk_management.propfirmaccount')),
            ],
            options={
                'verbose_name': 'Prop Firm Payout',
                'verbose_name_plural': 'Prop Firm Payouts',
                'ordering': ['-request_date'],
            },
        ),
    ]
