# Generated by Django 4.1.13 on 2026-02-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, help_text='Specific ticker this news is about', max_length=20, null=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('headline', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('sentiment_score', models.DecimalField(decimal_places=4, default=0.0, help_text='Range: -1.0 (Bearish) to 1.0 (Bullish)', max_digits=5)),
                ('sentiment_confidence', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='OHLCVBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], db_index=True, max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=15)),
                ('high', models.DecimalField(decimal_places=6, max_digits=15)),
                ('low', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='alpaca', max_length=30)),
            ],
            options={
                'verbose_name': 'OHLCV Bar',
                'verbose_name_plural': 'OHLCV Bars',
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
